### ISSUE TITLE
Python error on krita flatpak (linux)

### ISSUE THREAD

**Issue by starget24** [Aqaao/DockerUnderCursor#2]
So i just installed the plugin using the scrip importer tool in krita, and everytime i use i press the keyboard shortcut to use the plugin this appears 

![image](https://user-images.githubusercontent.com/92924912/210153996-b9c2b5cd-f5be-46f1-be64-b4f88dafb7ea.png)

Here is the log in more detail

```
TypeError
Python 3.10.6: /usr/bin/python3
Sat Dec 31 14:29:54 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py in toggleDockerStatus(self=<dockerundercursor.dockertogglemanager.DockerToggleManager object>)
  154     def toggleDockerStatus(self):
  155         if self.widget.isHidden():
  156             self.setToShow()
  157         elif self.widget.isFloating():
  158             if self.pinned:
self = <dockerundercursor.dockertogglemanager.DockerToggleManager object>
self.setToShow = <bound method DockerToggleManager.setToShow of <....dockertogglemanager.DockerToggleManager object>>

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py in setToShow(self=<dockerundercursor.dockertogglemanager.DockerToggleManager object>)
   79         if not self.widget.isFloating():
   80             self.widget.setFloating(True)
   81         self.moveDocker()
   82         self.widget.show()
   83 
self = <dockerundercursor.dockertogglemanager.DockerToggleManager object>
self.moveDocker = <bound method DockerToggleManager.moveDocker of ....dockertogglemanager.DockerToggleManager object>>

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py in moveDocker(self=<dockerundercursor.dockertogglemanager.DockerToggleManager object>)
  145 
  146     def moveDocker(self):
  147         dockerpos = self.targetPotion(QCursor.pos())
  148         if self.CLAMPPOSITION == "True":
  149             self.widget.move(self.checkPosition(dockerpos))
dockerpos undefined
self = <dockerundercursor.dockertogglemanager.DockerToggleManager object>
self.targetPotion = <bound method DockerToggleManager.targetPotion o....dockertogglemanager.DockerToggleManager object>>
global QCursor = <class 'PyQt5.QtGui.QCursor'>
QCursor.pos = <built-in function pos>

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py in targetPotion(self=<dockerundercursor.dockertogglemanager.DockerToggleManager object>, pos=PyQt5.QtCore.QPoint(932, 375))
   56         if self.mousepos:
   57             return QPoint(pos.x()-self.mousepos.x(),pos.y()-self.mousepos.y())
   58         return QPoint(pos.x()-self.widget.width()/2,pos.y()-self.widget.height()/2)
   59 
   60     def setToFloating(self):
global QPoint = <class 'PyQt5.QtCore.QPoint'>
pos = PyQt5.QtCore.QPoint(932, 375)
pos.x = <built-in method x of QPoint object>
self = <dockerundercursor.dockertogglemanager.DockerToggleManager object>
self.widget = <PyQt5.QtWidgets.QDockWidget object>
self.widget.width = <built-in method width of QDockWidget object>
pos.y = <built-in method y of QPoint object>
self.widget.height = <built-in method height of QDockWidget object>
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  Q...: QPoint): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py", line 156, in toggleDockerStatus
    self.setToShow()
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py", line 81, in setToShow
    self.moveDocker()
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py", line 147, in moveDocker
    dockerpos = self.targetPotion(QCursor.pos())
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/dockerundercursor/dockertogglemanager.py", line 58, in targetPotion
    return QPoint(pos.x()-self.widget.width()/2,pos.y()-self.widget.height()/2)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'
```
---------------------------------------
I don't know if this affected it but i had more plugins enable when this error came out, disable them and still got an error, this probably has to do with the python version krita bundles but i can't use the one provided by my package manager cause that version has the python bindings stripped from the build. 
If this is indeed a krita problem then feel free to close the issue, i want to make sure this problem is on krita part.

**Comment by Aqaao** [comment]
I'm not sure where this error is coming from .
but, you might try modifying dockertogglemanager.py
line 55 :
``` python
    def targetPotion(self,pos):
        if self.mousepos:
            return QPoint(pos.x()-self.mousepos.x(),pos.y()-self.mousepos.y())
        return QPoint(pos.x()-self.widget.width()/2,pos.y()-self.widget.height()/2)
```
change to :
``` python
    def targetPotion(self,pos):
        if self.mousepos:
            return QPoint(int(pos.x()-self.mousepos.x()),int(pos.y()-self.mousepos.y()))
        return QPoint(int(pos.x()-self.widget.width()/2),int(pos.y()-self.widget.height()/2))
```

**Comment by starget24** [comment]
Applying this solve the problem, and now the plugin is working as intended with no errors, thank you for replying.
I wonder if it would cause a problem to push it into the main.

**Comment by Aqaao** [comment]
This doesn't cause problems. I pushed it.
