### ISSUE TITLE
TypeError: 'Geometry' object is not callable

### ISSUE THREAD

**Issue by tanshoku** [Aqaao/DockerUnderCursor#4]
Crashes when i try to use this with the [Pigment.o plugin](https://github.com/EyeOdin/Pigment.O), works fine with other plugins and built-in dockers. Not sure if i should file the bug there or here, but most of the traceback seems related to this plugin:

```
TypeError
Python 3.12.6: /usr/bin/python3
Sat Sep 28 01:59:37 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/_________/.local/share/krita/pykrita/dockerundercursor/docker_auto_hide_filter.py in eventFilter(self=<dockerundercursor.docker_auto_hide_filter.DockerAutoHideFilter object>, obj=<pigment_o.pigment_o_docker.PigmentO_Docker object>, event=<PyQt5.QtCore.QEvent object>)
   24                 # Leaves docker event.
   25                 if event.type() == QEvent.Leave:
   26                     if not self.docker_manager.is_cursor_in_docker():
   27                         if self.docker_manager.pinned:
   28                             if self.docker_manager.leave:
self = <dockerundercursor.docker_auto_hide_filter.DockerAutoHideFilter object>
self.docker_manager = <dockerundercursor.docker_visibility_toggler.DockerVisibilityToggler object>
self.docker_manager.is_cursor_in_docker = <bound method DockerVisibilityToggler.is_cursor_...sibility_toggler.DockerVisibilityToggler object>>

 /home/_________/.local/share/krita/pykrita/dockerundercursor/docker_visibility_toggler.py in is_cursor_in_docker(self=<dockerundercursor.docker_visibility_toggler.DockerVisibilityToggler object>)
  148             return False
  149         pos = self.widget.mapFromGlobal(QCursor.pos())
  150         geometry = self.widget.geometry()
  151         geometry.moveTo(0, 0)
  152         if geometry.contains(pos):
geometry undefined
self = <dockerundercursor.docker_visibility_toggler.DockerVisibilityToggler object>
self.widget = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.widget.geometry = <pigment_o.pigment_o_calculations.Geometry object>
TypeError: 'Geometry' object is not callable
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __getstate__ = <built-in method __getstate__ of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    add_note = <built-in method add_note of TypeError object>
    args = ("'Geometry' object is not callable",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/_________/.local/share/krita/pykrita/dockerundercursor/docker_auto_hide_filter.py", line 26, in eventFilter
    if not self.docker_manager.is_cursor_in_docker():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/_________/.local/share/krita/pykrita/dockerundercursor/docker_visibility_toggler.py", line 150, in is_cursor_in_docker
    geometry = self.widget.geometry()
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Geometry' object is not callable
```

Operating system is Debian Testing, running xfce, on a multi-monitor setup. Krita is from apt, not flatpack or appimage.

**Comment by Aqaao** [comment]
This is a Pigment's bug.

https://github.com/EyeOdin/Pigment.O/issues/22

**Comment by Aqaao** [comment]
https://github.com/Aqaao/DockerUnderCursor/commit/617e8b011d49b13ff752e970e47db7a8d8ce5bba
Fixed.
